using System;

class MyException:ApplicationException
{
    public void MyDivideException()
    {
        Console.WriteLine("Exception Occured, Divisor should not be zero");
    }
}
 class Class1
{
   public static void Main() 
  {
        int x = 10;
        int y = 0;
        int z ;
        try
        {
            if(y==0)
            {
                throw new MyException();
            }
        }
catch(MyException ex)
{
    ex.MyDivideException();
}
  }
    }
